# Nodejs Base image

FROM node:12

WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH

# install and app dependencies

COPY package*.json ./

RUN npm install

RUN npm install -g @angular/cli

# add app

COPY . /app

CMD ng serve

